### ISSUE TITLE
Possible pyrecswitch in Home Assistant?

### ISSUE THREAD

**Issue by gianky69** [marcolertora/pyrecswitch#1]
Could it be possible to integrate your work within Home Assistant?
Thanks for your work!!!

**Comment by marcolertora** [comment]
Hi, I open a pull request to hass with the integration. You can find the code in my hass fork.

**Comment by gianky69** [comment]
Thanks
++++++++++++++++++++++++++++++++++++++++++++++++++++++
Il blog di mountain bike MIB: mib-trieste.it
Il mio piccolo blog fotografico: giancarlomassari.blogspot.com



Il giorno lun 3 set 2018 alle ore 23:12 marcolertora <
notifications@github.com> ha scritto:
